CREATE TABLE chats (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    description TEXT,
    type VARCHAR(10) CHECK(type IN ('GROUP', 'PRIVATE')),
    owner_id bigint,
    user1_id bigint,
    user2_id bigint,
    created_at TIMESTAMP
);

CREATE TABLE chat_participants (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);

CREATE TABLE messages (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE
);