spring:
  application:
    name: Front

  profiles:
    active: local

  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher
    hidden method:
      filter:
        enabled: true

jwt: ${TOKEN}
