CREATE TABLE notifications (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    type varchar(25) NOT NULL,
    msg text,
    created_at timestamp
);


CREATE TABLE subscriptions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint,
    sub_type varchar(25) NOT NULL,
    active boolean DEFAULT TRUE
);