CREATE TABLE chats (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_participants (
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (chat_id, user_id),
    FOREIGN KEY (chat_id) REFERENCES chats(id)
);

CREATE TABLE messages (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    chat_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (chat_id) REFERENCES chats(id)
);