spring:
  datasource:
    url: ${DB_LOCAL_URL}

server:
  port: ${LOCAL_SERVER_PORT}
  servlet:
    context-path: /

grpc:
  server:
    port: ${LOCAL_GRPC_PORT}

  client:
    GLOBAL:
      negotiation-type: plaintext
    message-service-client:
      address: ${MESSAGE_SERVICE_ADDRESS}
      negotiationType: PLAINTEXT

    notification-service-client:
      address: ${NOTIFICATION_SERVICE_ADDRESS}
      negotiationType: PLAINTEXT